apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagging-service
  namespace: oih-dev-ns
  labels:
    app: tagging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tagging-service
  template:
    metadata:
      labels:
        app: tagging-service
    spec:
      containers:
      - name: tagging-service
        image: cloudecosystem/tagging-service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3001
        envFrom:
        - configMapRef:
            name: tagging-service
        env:
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: tagging-service
                key: 'mongourl'
          - name: IAM_TOKEN
            valueFrom:
              secretKeyRef:
                name: tagging-service
                key: 'iamtoken'
        resources:
          limits:
            cpu: '0.1'
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3001
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3001
          initialDelaySeconds: 10
          timeoutSeconds: 1
