apiVersion: v1
kind: Service
metadata:
  labels:
    app: tagging-service
  name: tagging-service
  namespace: oih-dev-ns
spec:
  type: NodePort
  selector:
      app: tagging-service
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
